name: grill-names
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip:
    - naming
    - -e git+https://github.com/thegrill/sphinx.git@grill-intersphinx-uniqueref
    - sphinx_autodoc_typehints
    - sphinx_rtd_theme
