name: grill-names
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip:
    - naming
    - "git+https://github.com/sphinx-doc/sphinx.git@stable#egg=Sphinx1"
    - sphinx_autodoc_typehints
    - sphinx_rtd_theme
