name: grill-names
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip:
    - naming
    - "git+https://github.com/thegrill/sphinx.git@grill-intersphinx-uniqueref-fix#egg=Sphinx"
    - sphinx_autodoc_typehints
    - sphinx_rtd_theme
